version: '1.0'
stages:
  - "clone"
  - "build"
  - "gitops"
steps:
  main_clone:
    type: git-clone
    description: Cloning main repository...
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: clone
  build:
    title: Building Docker Image
    type: build
    image_name: racebook
    tag: '${{CF_BRANCH}}-${{CF_REVISION}}'
    dockerfile: Dockerfile
    stage: build
    registry: '${{ecr}}'
  clone_gitops:
    title: cloning gitops repo
    type: git-clone
    arguments:
      repo:  wohlig/playexch-gitops
      revision: uat
    stage: gitops
    when:
      branch:
        only:
          - siddhesh_working
  change_manifest:
    title: Update k8s manifest
    image: mikefarah/yq
    commands:
      - >-
        yq e '.spec.template.spec.containers[0].image =
        "444083742860.dkr.ecr.eu-central-1.amazonaws.com/racebook:${{CF_BRANCH}}-${{CF_REVISION}}"'
        -i deployment.apps/racebook.yaml
      - cat deployment.apps/racebook.yaml
    working_directory: '${{clone_gitops}}'
    stage: gitops
    when:
      branch:
        only:
          - siddhesh_working
  commit_and_push:
    title: Commit manifest
    type: git-commit
    stage: gitops
    arguments:
      repo: wohlig/playexch-gitops
      git: Wohlig
      working_directory: /codefresh/volume/playexch-gitops/deployment.apps
      commit_message: Updated newer Image
      git_user_name: ${{CF_COMMIT_AUTHOR}}
      git_user_email: ${{CF_COMMIT_AUTHOR}}@wohlig.com
    when:
      branch:
        only:
          - siddhesh_working

